services:
  mercure:
    image: dunglas/mercure
    environment:
      MERCURE_JWT_SECRET: '%env(MERCURE_JWT_SECRET)%'
      MERCURE_PUBLISHER_JWT_KEY: '%env(MERCURE_JWT_SECRET)%'
      MERCURE_SUBSCRIBER_JWT_KEY: '%env(MERCURE_JWT_SECRET)%'
      SERVER_NAME: ':80'
      MERCURE_ALLOW_ANONYMOUS: '1'
      MERCURE_CORS_ALLOWED_ORIGINS: 'http://localhost:3000'
    ports:
      - '3001:80'
